SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
-- ----------------------------
-- Table structure for test
-- Table auto generated by pika
-- ----------------------------
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test`  (
  `context` varchar(255) NOT NULL COMMENT '内容!!!!!!!!!',
  `buer` bit(1) NOT NULL,
  `id` mediumint NOT NULL COMMENT '主键id',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '修改时间',
 PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '这是一个test表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;