SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
-- ----------------------------
-- Table structure for ${tableName}
-- Table auto generated by pikaGenerator
-- Table created since ${generateTime}
-- ----------------------------
DROP TABLE IF EXISTS `${tableName}`;
CREATE TABLE `${tableName}`  (
 <#list cols as col>
  `${col.colName}` ${col.colType}<#if col.colLength ??>(${col.colLength})</#if><#if !col.nullable> NOT</#if> NULL<#if col.isAutoIncrement> AUTO_INCREMENT</#if><#if col.colComment ??> COMMENT '${col.colComment}'</#if>,
 </#list>
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '修改时间',
 PRIMARY KEY (<#list primaryKeys as key>`${key}`<#if key_has_next>,</#if></#list>) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci<#if tableComment ??> COMMENT = '${tableComment}'</#if> ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;